version: "3"
services:
  master:
    image: spark_hive_scala.2.12:3.1.2
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master && cd $HIVE_HOME/bin && ./hiveserver2 --hiveconf hive.server2.enable.doAs=false
    hostname: master
    env_file:
      - ./hadoop-hive.env
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 192.168.56.114
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data
    networks:
      - hadoop-network
  worker:
    image: spark_hive_scala.2.12:3.1.2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: 192.168.56.114
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
    networks:
      - hadoop-network
networks:
  hadoop-network:
    external:
      name: dock_net