version: "3"
services:
  hive-server:
    image: hive:3.1.2
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://192.168.56.114/metastore"
      SERVICE_PRECONDITION: "192.168.56.114:9083"
    ports:
      - "10000:10000"
    networks:
      - hadoop-network
  hive-metastore:
    image: hive:3.1.2
    env_file:
      - ./hadoop-hive.env
    command:   /opt/hive/bin/hive --service metastore 
    environment:
      SERVICE_PRECONDITION: "192.168.56.114:50070 192.168.56.114:50075 192.168.56.114:5432"
    ports:
      - "9083:9083"
    networks:
      - hadoop-network
  postgres:
    build:
      context: ./ms_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aymane
      POSTGRES_PASSWORD: aymane
    networks:
      - hadoop-network
networks:
  hadoop-network:
    external:
      name: dock_net