version: "3"
services:
  cassandra:
    build: ./
    #image: cassandra:4.0.7
    command: /usr/bin/start-cassandra
    hostname: cassandra
    ports:
      - 9160:9160
      - 9042:9042
    environment:
      DNS: localhost
    networks:
      - hadoop-network
networks:
  hadoop-network:
    external:
      name: dock_net